
package computerservice;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class AddUserPanel extends javax.swing.JPanel {

    /** Creates new form AddUserPanel */
    private Administrator admin;
    private UserList uList;

    public AddUserPanel(Administrator admin, UserList uList) {
        this.admin = admin;
        this.uList = uList;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usrGroup = new javax.swing.ButtonGroup();
        addUsrPanel = new javax.swing.JPanel();
        usrnameLabel = new javax.swing.JLabel();
        pwdLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        surnameLabel = new javax.swing.JLabel();
        admRadio = new javax.swing.JRadioButton();
        modRadio = new javax.swing.JRadioButton();
        scrRadio = new javax.swing.JRadioButton();
        hrdRadio = new javax.swing.JRadioButton();
        sftRadio = new javax.swing.JRadioButton();
        usrnameField = new javax.swing.JTextField();
        pwdField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        surnameField = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        warningLabel = new javax.swing.JLabel();

        addUsrPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addUsrPanel.setEnabled(false);

        usrnameLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        usrnameLabel.setText("Username");

        pwdLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        pwdLabel.setText("Password");

        nameLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        nameLabel.setText("Όνομα");

        surnameLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        surnameLabel.setText("Επίθετο");

        usrGroup.add(admRadio);
        admRadio.setFont(new java.awt.Font("Tahoma", 0, 14));
        admRadio.setText("Διαχειριστής");

        usrGroup.add(modRadio);
        modRadio.setFont(new java.awt.Font("Tahoma", 0, 14));
        modRadio.setText("Συντονιστής");

        usrGroup.add(scrRadio);
        scrRadio.setFont(new java.awt.Font("Tahoma", 0, 14));
        scrRadio.setText("Γραμματέας");

        usrGroup.add(hrdRadio);
        hrdRadio.setFont(new java.awt.Font("Tahoma", 0, 14));
        hrdRadio.setText("Τεχνικός Υλικού");

        usrGroup.add(sftRadio);
        sftRadio.setFont(new java.awt.Font("Tahoma", 0, 14));
        sftRadio.setText("Τεχνικός Λογισμικού");

        addBtn.setText("Προσθήκη");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        warningLabel.setFont(new java.awt.Font("Tahoma", 1, 14));
        warningLabel.setForeground(new java.awt.Color(255, 0, 51));
        warningLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout addUsrPanelLayout = new javax.swing.GroupLayout(addUsrPanel);
        addUsrPanel.setLayout(addUsrPanelLayout);
        addUsrPanelLayout.setHorizontalGroup(
            addUsrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addUsrPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(addUsrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addUsrPanelLayout.createSequentialGroup()
                        .addComponent(usrnameLabel)
                        .addGap(122, 122, 122)
                        .addComponent(usrnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addUsrPanelLayout.createSequentialGroup()
                        .addComponent(pwdLabel)
                        .addGap(125, 125, 125)
                        .addComponent(pwdField, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addUsrPanelLayout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addGap(140, 140, 140)
                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addUsrPanelLayout.createSequentialGroup()
                        .addComponent(surnameLabel)
                        .addGap(136, 136, 136)
                        .addComponent(surnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addUsrPanelLayout.createSequentialGroup()
                        .addComponent(admRadio)
                        .addGap(73, 73, 73)
                        .addComponent(hrdRadio))
                    .addGroup(addUsrPanelLayout.createSequentialGroup()
                        .addComponent(modRadio)
                        .addGap(69, 69, 69)
                        .addComponent(sftRadio))
                    .addGroup(addUsrPanelLayout.createSequentialGroup()
                        .addComponent(scrRadio)
                        .addGap(226, 226, 226)
                        .addComponent(addBtn))))
            .addComponent(warningLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );
        addUsrPanelLayout.setVerticalGroup(
            addUsrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addUsrPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(addUsrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usrnameLabel)
                    .addComponent(usrnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(addUsrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pwdLabel)
                    .addComponent(pwdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(addUsrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(addUsrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(surnameLabel)
                    .addGroup(addUsrPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(surnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(addUsrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(admRadio)
                    .addComponent(hrdRadio))
                .addGap(3, 3, 3)
                .addGroup(addUsrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modRadio)
                    .addComponent(sftRadio))
                .addGap(3, 3, 3)
                .addGroup(addUsrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrRadio)
                    .addGroup(addUsrPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(addBtn)))
                .addGap(18, 18, 18)
                .addComponent(warningLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 12, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(addUsrPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(19, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(addUsrPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        String username = null;
        String password = null;
        String name = null;
        String surname = null;
        String type = null;
        try {
            username = usrnameField.getText();
            password = pwdField.getText();
            name = nameField.getText();
            surname = surnameField.getText();
            type = new String();
            if (admRadio.isSelected()) {
                type = "Administrator";
            } else if (modRadio.isSelected()) {
                type = "Moderator";
            } else if (scrRadio.isSelected()) {
                type = "Secretary";
            } else if (hrdRadio.isSelected()) {
                type = "Hardware Technician";
            } else if (sftRadio.isSelected()) {
                type = "Software Technician";
            }
            if(!(username.equals("")) && !(password.equals("")) && !(name.equals("")) && !(surname.equals("")) && type!=null)
            {
            if(admin.addUser(username, password, name, surname, type, uList))
            {
            uList.Save();
            this.setVisible(false);
            JOptionPane.showMessageDialog(null, "Ο χρήστης προστέθηκε επιτυχώς.","Information", JOptionPane.INFORMATION_MESSAGE);}
            else { warningLabel.setText("Υπάρχει χρήστης με το ίδιο Username.");}
            }
            else
            warningLabel.setText("Υπάρχουν κενά πεδία.");
        } catch (NullPointerException e) {
            warningLabel.setText("Υπάρχουν κενά πεδία.");
        }

}//GEN-LAST:event_addBtnActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JPanel addUsrPanel;
    private javax.swing.JRadioButton admRadio;
    private javax.swing.JRadioButton hrdRadio;
    private javax.swing.JRadioButton modRadio;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField pwdField;
    private javax.swing.JLabel pwdLabel;
    private javax.swing.JRadioButton scrRadio;
    private javax.swing.JRadioButton sftRadio;
    private javax.swing.JTextField surnameField;
    private javax.swing.JLabel surnameLabel;
    private javax.swing.ButtonGroup usrGroup;
    private javax.swing.JTextField usrnameField;
    private javax.swing.JLabel usrnameLabel;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
}
