
package computerservice;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.JFrame;


public class AdminPanel extends javax.swing.JPanel {

    /** Creates new form AdminPanel */
    private Administrator admin;
    private UserList uList;
    private TaskList tList;
    private JFrame frame;

    public AdminPanel(Administrator admin, UserList uList,TaskList tList,JFrame  frame)
    {
        this.frame=frame;
        this.tList=tList;
        this.uList = uList;
        this.admin = admin;
        initComponents();
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usrGroup = new javax.swing.ButtonGroup();
        actionMenu = new javax.swing.JComboBox();
        execBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        logBtn = new javax.swing.JButton();
        defaultPanel = new javax.swing.JPanel();

        actionMenu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Επιλογή ενέργειας--", "Καταχώρηση Χρήστη", "Προβολή Χρηστών" }));

        execBtn.setText("Εκτέλεση");
        execBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                execBtnActionPerformed(evt);
            }
        });

        logBtn.setText("Logout");
        logBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout defaultPanelLayout = new javax.swing.GroupLayout(defaultPanel);
        defaultPanel.setLayout(defaultPanelLayout);
        defaultPanelLayout.setHorizontalGroup(
            defaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );
        defaultPanelLayout.setVerticalGroup(
            defaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 331, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(actionMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(execBtn))
                                .addGap(18, 18, 18)
                                .addComponent(defaultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(logBtn))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(actionMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 288, Short.MAX_VALUE)
                        .addComponent(execBtn))
                    .addComponent(defaultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logBtn)
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void execBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_execBtnActionPerformed
        String selection = (String)actionMenu.getSelectedItem();
        defaultPanel.removeAll();
        if (selection.equals("Καταχώρηση Χρήστη"))
        {
            AddUserPanel usrpnl = new AddUserPanel(admin, uList);
            defaultPanel.setLayout(new BorderLayout());
            defaultPanel.add(usrpnl);
            this.validate();
        }
        else if (selection.equals("Προβολή Χρηστών"))
        {
            ShowUsersPanel usrpnl = new ShowUsersPanel(uList,admin);
            defaultPanel.setLayout(new BorderLayout());
            defaultPanel.add(usrpnl);
            this.validate();
        }
    }//GEN-LAST:event_execBtnActionPerformed

    private void logBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logBtnActionPerformed
        this.setVisible(false);
        frame.setSize(400, 300);
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int X = (screen.width / 2) - (400/2); // Center horizontally.
        int Y = (screen.height / 2) - (300/2); // Center vertically.
        frame.setLocation(new Point(X,Y));
        frame.add(new LoginPane(uList,frame,tList));
    }//GEN-LAST:event_logBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox actionMenu;
    private javax.swing.JPanel defaultPanel;
    private javax.swing.JButton execBtn;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logBtn;
    private javax.swing.ButtonGroup usrGroup;
    // End of variables declaration//GEN-END:variables

}
