package computerservice;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.JFrame;


public class ModPanel extends javax.swing.JPanel {

    /** Creates new form AdminPanel */
    private Moderator mod;
    private UserList uList;
    private TaskList tList;
    private ShowOpenTaskPanel openPanel;
    private ShowInProgressPanel proPanel;
    private AssignPanel assPanel;
    private JFrame frame;

    public ModPanel(Moderator mod, UserList uList,TaskList tList,JFrame frame)
    {
        this.frame=frame;
        this.uList = uList;
        this.tList=tList;
        this.mod=mod;
        openPanel=new ShowOpenTaskPanel(mod,tList);
        proPanel=new ShowInProgressPanel(mod,tList);
        assPanel=new AssignPanel(mod,uList,tList);
        openPanel.setVisible(false);
        proPanel.setVisible(false);
        assPanel.setVisible(false);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usrGroup = new javax.swing.ButtonGroup();
        actionMenu = new javax.swing.JComboBox();
        execBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        logBtn = new javax.swing.JButton();
        defaultPanel = new javax.swing.JPanel();

        actionMenu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Επιλογή ενέργειας--", "Προβολή ανοιχτών εργασιών", "Προβολή εργασιών σε εξέληξη", "Ανάθεση εργασίας" }));

        execBtn.setText("Εκτέλεση");
        execBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                execBtnActionPerformed(evt);
            }
        });

        logBtn.setText("Logout");
        logBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout defaultPanelLayout = new javax.swing.GroupLayout(defaultPanel);
        defaultPanel.setLayout(defaultPanelLayout);
        defaultPanelLayout.setHorizontalGroup(
            defaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );
        defaultPanelLayout.setVerticalGroup(
            defaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 331, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logBtn)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(actionMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(execBtn))
                        .addGap(18, 18, 18)
                        .addComponent(defaultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actionMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(defaultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logBtn)
                .addGap(12, 12, 12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(331, Short.MAX_VALUE)
                .addComponent(execBtn)
                .addGap(67, 67, 67))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void execBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_execBtnActionPerformed
        String selection = (String)actionMenu.getSelectedItem();
        if (selection.equals("Προβολή ανοιχτών εργασιών"))
        {
            proPanel.setVisible(false);
            assPanel.setVisible(false);
            if(!openPanel.isVisible())
            {
                openPanel=new ShowOpenTaskPanel(mod,tList);
                defaultPanel.setLayout(new BorderLayout());
                defaultPanel.add(openPanel);
                this.validate();
            }
        }
        else if(selection.equals("Προβολή εργασιών σε εξέληξη"))
        {
            assPanel.setVisible(false);
            openPanel.setVisible(false);
            if(!proPanel.isVisible())
            {
                proPanel=new ShowInProgressPanel(mod,tList);
                defaultPanel.setLayout(new BorderLayout());
                defaultPanel.add(proPanel);
                this.validate();
            }
        }
        else if(selection.equals("Ανάθεση εργασίας"))
        {
            openPanel.setVisible(false);
            proPanel.setVisible(false);
            if(!assPanel.isVisible())
            {
                assPanel=new AssignPanel(mod,uList,tList);
                defaultPanel.setLayout(new BorderLayout());
                defaultPanel.add(assPanel);
                this.validate();
            }
        }
    }//GEN-LAST:event_execBtnActionPerformed

    private void logBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logBtnActionPerformed
        this.setVisible(false);
        frame.setSize(400, 300);
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int X = (screen.width / 2) - (400/2); // Center horizontally.
        int Y = (screen.height / 2) - (300/2); // Center vertically.
        frame.setLocation(new Point(X,Y));
        frame.add(new LoginPane(uList,frame,tList));
    }//GEN-LAST:event_logBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox actionMenu;
    private javax.swing.JPanel defaultPanel;
    private javax.swing.JButton execBtn;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logBtn;
    private javax.swing.ButtonGroup usrGroup;
    // End of variables declaration//GEN-END:variables

}
